name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/namelesslang
          asset_name: nameless-linux-amd64
          tag: ${{ env.GITHUB_REF }}
          overwrite: true
